server:
  port: 8085

spring:
  application:
    name: Yorick Application - User service
  datasource:
    url: jdbc:postgresql://localhost:5443/yorick
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8086/oauth2/jwks
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/


